baseURL = "https://bihela.github.io/gh-deployment-workflow/"
languageCode = "en-us"
title = "Bihela's DevOps Portfolio"
theme = "gokarna"

[params]
  description = "Portfolio showcasing my DevOps projects and skills"
  avatarURL = "images/avatar.jpg"
  avatarSize = "size-m"
  showSidebar = true
  socialIcons = [
    { name = "github", url = "https://github.com/Bihela" },
    { name = "linkedin", url = "https://linkedin.com/in/bihela" }
  ]
  footer = "Built with Hugo and Gokarna | Hosted on GitHub Pages"
  accentColor = "#007bff"
  enableSearch = true
  themeStyle = "dark" # Enable default dark mode

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/posts/projects/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/posts/about/"
    weight = 3